import React from 'react';
import { Container, Row, Col, Card } from 'react-bootstrap';
import { Bar, Pie, Line } from 'react-chartjs-2';
import {
  Chart as ChartJS,
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  Tooltip as ChartTooltip,
  Legend,
  ArcElement,
  PointElement,
  LineElement
} from 'chart.js';

// Register ChartJS components
ChartJS.register(
  CategoryScale,
  LinearScale,
  BarElement,
  Title,
  ChartTooltip,
  Legend,
  ArcElement,
  PointElement,
  LineElement
);

const PrintStatistics = React.forwardRef(({ stats, prepareStatusData, prepareCategoryData, prepareTimeSeriesData }, ref) => {
  return (
    <div ref={ref} className="p-4">
      <h1 className="text-center mb-4">Hazard Reports Statistics</h1>
      <p className="text-muted text-center mb-4">
        Generated on {new Date().toLocaleDateString()} at {new Date().toLocaleTimeString()}
      </p>
      
      {/* Summary Cards */}
      <Row className="mb-4 g-3">
        <Col md={3} sm={6}>
          <Card className="text-center h-100">
            <Card.Body>
              <h2 className="text-primary">{stats?.totalReports || 0}</h2>
              <p className="text-muted mb-0">Total Reports</p>
            </Card.Body>
          </Card>
        </Col>
        <Col md={3} sm={6}>
          <Card className="text-center h-100">
            <Card.Body>
              <h2 className="text-success">{stats?.resolvedReports || 0}</h2>
              <p className="text-muted mb-0">Resolved</p>
            </Card.Body>
          </Card>
        </Col>
        <Col md={3} sm={6}>
          <Card className="text-center h-100">
            <Card.Body>
              <h2 className="text-warning">{stats?.pendingReports || 0}</h2>
              <p className="text-muted mb-0">Pending</p>
            </Card.Body>
          </Card>
        </Col>
        <Col md={3} sm={6}>
          <Card className="text-center h-100">
            <Card.Body>
              <h2 className="text-danger">{stats?.escalatedReports || 0}</h2>
              <p className="text-muted mb-0">Escalated</p>
            </Card.Body>
          </Card>
        </Col>
      </Row>
      
      {/* Charts */}
      <Row className="mb-4">
        <Col md={6}>
          <h4>Reports by Status</h4>
          <div style={{ height: '300px' }}>
            <Pie data={prepareStatusData()} />
          </div>
        </Col>
        <Col md={6}>
          <h4>Reports by Category</h4>
          <div style={{ height: '300px' }}>
            <Bar data={prepareCategoryData()} />
          </div>
        </Col>
      </Row>
      
      <Row className="mb-4">
        <Col>
          <h4>Reports Over Time</h4>
          <div style={{ height: '300px' }}>
            <Line data={prepareTimeSeriesData()} />
          </div>
        </Col>
      </Row>
      
      <div className="mt-4 text-muted text-center">
        <p>Report generated by AddisCare - Hazard Reporting System</p>
      </div>
    </div>
  );
});

export default PrintStatistics;
